[package]
name = "joseph/rojotreetemplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Observers = "sleitnick/observers@0.5.0"
ProfileStore = "vyon/profilestore@1.0.3"
TopbarPlus = "1foreverhd/topbarplus@3.4.0"
Networker = "leifstout/networker@0.3.0"
Signal = "sleitnick/signal@2.0.0"
Conch = "alicesaidhi/conch@0.3.1"
ConchUi = "alicesaidhi/conch-ui@0.3.1"